// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FSP_API.Context;

#nullable disable

namespace FSP_API.Migrations
{
    [DbContext(typeof(ContexDb))]
    [Migration("20230302141703_Tercera")]
    partial class Tercera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSP_API.Modelos.AnimalesCatalogo", b =>
                {
                    b.Property<int>("AnimalesCatalogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalesCatalogoId"));

                    b.Property<string>("CAlimentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDescripcionAnimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDistribucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEspecie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHabitat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHabitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CImagenAnimal")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CNombreComun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CReproduccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DistribucionMapa")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AnimalesCatalogoId");

                    b.ToTable("AnimalesCatalogos");
                });

            modelBuilder.Entity("FSP_API.Modelos.ModeloAnimales", b =>
                {
                    b.Property<int>("ModeloAnimalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloAnimalesId"));

                    b.Property<int>("AnimalesCatalogoId")
                        .HasColumnType("int");

                    b.Property<string>("CondicionAnimal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcionanimal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("ImagenAnimal")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ModeloUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeloAnimalesId");

                    b.HasIndex("AnimalesCatalogoId");

                    b.HasIndex("ModeloUsuarioId");

                    b.ToTable("ModeloAnimales");
                });

            modelBuilder.Entity("FSP_API.Modelos.ModeloUsuario", b =>
                {
                    b.Property<int>("ModeloUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloUsuarioId"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Otralocalidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeloUsuarioId");

                    b.ToTable("ModeloUsuarios");
                });

            modelBuilder.Entity("FSP_API.Modelos.ModeloAnimales", b =>
                {
                    b.HasOne("FSP_API.Modelos.AnimalesCatalogo", null)
                        .WithMany("ModeloAnimales")
                        .HasForeignKey("AnimalesCatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSP_API.Modelos.ModeloUsuario", null)
                        .WithMany("AnimalModels")
                        .HasForeignKey("ModeloUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSP_API.Modelos.AnimalesCatalogo", b =>
                {
                    b.Navigation("ModeloAnimales");
                });

            modelBuilder.Entity("FSP_API.Modelos.ModeloUsuario", b =>
                {
                    b.Navigation("AnimalModels");
                });
#pragma warning restore 612, 618
        }
    }
}
